# Generated by Django 3.0.1 on 2020-01-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Address', models.CharField(max_length=50)),
                ('Phone', models.IntegerField()),
                ('Description', models.TextField(max_length=250)),
            ],
        ),
    ]
