# Generated by Django 3.0.3 on 2020-02-10 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faceofnepal', '0002_tourist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Guide', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_guide', to='faceofnepal.Freelancer')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='faceofnepal.Freelancer')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
                ('company_location', models.CharField(max_length=20)),
                ('package_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cash', models.IntegerField()),
                ('Cheque', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Visitor_Name', models.CharField(max_length=20)),
                ('Visitor_Email', models.EmailField(max_length=30)),
                ('Visitor_Mobile_No', models.IntegerField()),
                ('Visitor_address', models.CharField(max_length=30)),
                ('Guide', models.ManyToManyField(blank=True, related_name='guide', to='faceofnepal.Freelancer')),
            ],
        ),
        migrations.DeleteModel(
            name='Tourist',
        ),
    ]
